name: moviewave
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  flutter_svg: ^2.1.0
  equatable: ^2.0.7
  loader_overlay: ^5.0.0
  loading_indicator: ^3.1.1
  ming_cute_icons: ^0.0.7
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
